# Generated by Django 5.2.1 on 2025-06-11 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_view', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
